name: Create Atlas
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Download Unciv
        run: wget https://github.com/yairm210/Unciv/releases/latest/download/Unciv.jar
        
      - name: Create Atlas
        run: java -jar Unciv.jar createAtlas
        
      - name: Commit Atlas
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Auto-generate atlas" || echo "No changes"
          git push
